name: glue
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohappyeyeballs=2.4.3
  - aiosignal=1.3.1
  - amply=0.1.6
  - anndata=0.9.2
  - anyio=4.4.0
  - appdirs=1.4.4
  - argcomplete=3.4.0
  - argh=0.31.2
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=2.4.1
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attmap=0.13.2
  - attrs=23.2.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.1
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.3
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.21.0
  - aws-sdk-cpp=1.10.57
  - babel=2.14.0
  - backcall=0.2.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - bcrypt=4.2.0
  - beautifulsoup4=4.12.3
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.38
  - biopython=1.83
  - blas=2.120
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blosc=1.21.5
  - bokeh=3.1.1
  - boto3=1.35.72
  - botocore=1.35.99
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bwidget=1.10.1
  - bx-python=0.13.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - c-blosc2=2.12.0
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.18.0
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.12
  - colorama=0.4.6
  - comm=0.2.2
  - configargparse=1.7
  - connection_pool=0.0.3
  - contourpy=1.1.1
  - cooler=0.9.3
  - cryptography=43.0.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - curl=8.8.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2023.5.0
  - dask-core=2023.5.0
  - datrie=0.8.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distributed=2023.5.0
  - docutils=0.20.1
  - dpath=2.2.0
  - dropbox=12.0.2
  - eido=0.2.4
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - faiss=1.7.4
  - faiss-gpu=1.7.4
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.6.0
  - ftputil=5.1.0
  - future=1.0.0
  - gcc_impl_linux-64=12.1.0
  - gdk-pixbuf=2.42.12
  - get-annotations=0.1.2
  - gffutils=0.13
  - gflags=2.2.2
  - gfortran_impl_linux-64=12.1.0
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.3.0
  - google-api-core=2.22.0
  - google-api-python-client=2.151.0
  - google-auth=2.35.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.18.2
  - google-crc32c=1.1.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - graphite2=1.3.13
  - graphviz=9.0.0
  - grpcio=1.54.3
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=12.1.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.9.0
  - harfbuzz=8.5.0
  - hdf5=1.14.1
  - hicmatrix=17.2
  - hpack=4.0.0
  - htslib=1.20
  - httpcore=1.0.5
  - httplib2=0.22.0
  - httpx=0.27.0
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - igraph=0.10.12
  - importlib-metadata=7.1.0
  - importlib-resources=6.4.0
  - importlib_metadata=7.1.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - intervaltree=3.1.0
  - ipykernel=6.29.4
  - ipython=8.12.2
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - jupytext=1.16.5
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libarrow=12.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-devel_linux-64=12.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.2
  - libgomp=15.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.3
  - libhwloc=2.10.0
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libleidenalg=0.11.1
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libnuma=2.0.18
  - libopenblas=0.3.25
  - libopenssl-static=3.5.0
  - libpng=1.6.49
  - libprotobuf=3.21.12
  - librsvg=2.58.1
  - libsanitizer=12.1.0
  - libsodium=1.0.18
  - libsqlite=3.50.1
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=12.1.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.18.1
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - llvm-openmp=18.1.7
  - llvmlite=0.39.1
  - locket=1.0.0
  - logmuse=0.2.8
  - loompy=3.0.6
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - magma=2.6.2
  - make=4.4.1
  - mariadb-connector-c=3.4.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2022.2.1
  - msgpack-python=1.0.8
  - multidict=6.0.5
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - natsort=8.4.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nccl=2.22.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.1
  - ninja=1.12.1
  - nomkl=3.0
  - notebook-shim=0.2.4
  - numba=0.56.3
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - numpy_groupies=0.9.22
  - oauth2client=4.1.3
  - openblas=0.3.25
  - openjpeg=2.5.2
  - openssl=3.5.0
  - orc=1.9.0
  - overrides=7.7.0
  - packaging=24.1
  - pairix=0.3.8
  - pandas=1.4.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - paramiko=3.5.0
  - parse=1.20.2
  - parso=0.8.4
  - partd=1.4.1
  - patsy=0.5.6
  - pcre2=10.43
  - peppy=0.40.7
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.8.2
  - prettytable=3.11.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - proto-plus=1.25.0
  - protobuf=4.21.12
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pyarrow=12.0.1
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybedtools=0.10.0
  - pybigwig=0.3.22
  - pycparser=2.22
  - pyfaidx=0.8.1.1
  - pygenometracks=3.9
  - pygments=2.18.0
  - pygraphviz=1.11
  - pynacl=1.5.0
  - pynndescent=0.5.13
  - pynvml=11.5.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pysam=0.22.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytables=3.8.0
  - pytest=8.2.2
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-igraph=0.11.5
  - python-irodsclient=2.1.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.8
  - pytorch=1.13.1
  - pytorch-gpu=1.13.1
  - pytorch-ignite=0.4.8
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyvcf3=1.0.3
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - r-base=4.3.3
  - rdma-core=28.9
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - reretry=0.11.8
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.18.1
  - rpy2=3.5.11
  - rsa=4.9
  - s2n=1.3.49
  - s3transfer=0.10.4
  - samtools=1.20
  - scanpy=1.9.8
  - scglue=0.3.2
  - scikit-learn=1.3.0
  - scikit-misc=0.1.4
  - scipy=1.10.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - send2trash=1.8.3
  - session-info=1.0.0
  - setuptools=69.5.1
  - simplegeneric=0.8.1
  - simplejson=3.19.2
  - six=1.16.0
  - slacker=0.14.0
  - sleef=3.5.1
  - smart_open=7.0.5
  - smmap=5.0.0
  - snakemake=7.32.4
  - snakemake-minimal=7.32.4
  - snappy=1.1.10
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparse=0.15.4
  - sqlite=3.31.1
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - stdlib-list=0.10.0
  - stone=3.3.2
  - stopit=1.1.2
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.12.0
  - tblib=3.0.0
  - tensorboardx=2.6.2.2
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - throttler=1.2.2
  - tinycss2=1.3.0
  - tk=8.6.13
  - tktable=2.10
  - tomli=2.0.1
  - toolz=0.12.1
  - toposort=1.10
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.2
  - ubiquerg=0.8.0
  - ucsc-liftover=482
  - ucx=1.14.1
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uritemplate=4.1.1
  - urllib3=1.26.19
  - veracitools=0.1.3
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.9.4
  - yte=1.8.1
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - antlr4-python3-runtime==4.9.3
      - arboreto==0.1.6
      - boltons==24.0.0
      - certifi==2024.8.30
      - ctxcore==0.2.0
      - frozendict==2.4.4
      - gseapy==1.1.5
      - hydra==2.5
      - interlap==0.2.7
      - kaleido==0.2.1
      - mudata==0.2.3
      - multiprocessing-on-dill==3.5.0a4
      - muon==0.1.6
      - narwhals==1.28.0
      - numpy==1.23.3
      - omegaconf==2.3.0
      - plotly==6.0.0
      - pyscenic==0.12.1
      - socksio==1.0.0
      - uniport==1.2.2
prefix: /mnt/sdbd/home/zhoujin_gyj/anaconda3/envs/glue
